package ldjam.hamorigami.model;

public enum SpiritAnimationType {
   HOVERING_NORTH,
   HOVERING_WEST,
   HOVERING_EAST,
   HOVERING_SOUTH,

   IDLE_WEST,
   IDLE_EAST,

   FALLING_WEST,
   FALLING_EAST,

   ABSORBING_NORTH,
   ABSORBING_WEST,
   ABSORBING_EAST,
   ABSORBING_SOUTH;
}
